server:
  port: 8080

spring:
#  #静态资源处理
#  resources:
#    #启动默认静态资源处理
#    add-mappings: true
#    cache:
#      cachecontrol:
#        #缓存相应时间单位秒
#        max-age: 3600
#    chain:
#      #资源链启动缓存
#      cache: true
#      #启动资源链
#      enabled: true
#      #启动压缩资源
#      compressed: true
#      # h5的应用缓存
#      html-application-cache: true
#    static-locations: classpath:/static/


  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: wanzhiwen
    # 连接池 最快？
    hikari:
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲最大存活时间，默认600000（10分钟）
      idle-timeout: 1800000
      #最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间 0表示永久存活 默认30分钟
      max-lifetime: 1800000
      #连接超时时间 默认30秒
      connection-timeout: 30000
      #测试连接可用查询语句
      connection-test-query: SELECT 1

  redis:
    #服务器地址
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 8
        min-idle: 0



  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只能处理一个消息，处理完毕才能继续下一条
        prefetch: 1
        # 启动的时候是否默认启动容器
        auto-startup: true
        # 当被拒绝时是否重新加入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试 默认false
        enabled: true
        # 重试时间
        initial-interval: 1000ms
        # 重试最大次数
        max-attempts: 3
        # 重试最大间隔时间
        max-interval: 10000ms
        # 重试的间隔乘数 比如2.0 第一次等10s 第二次等20s 第三次等30s
        multiplier: 1

dubbo:
  application:
    name: payClient
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880

mybatis-plus:
  # Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis返回数据别名 默认别名是类名
  type-aliases-package: com.wzw.seckill.pojo

# mybatis SQL打印（方法接口所在的包 不是 mapper.xml）
logging:
  level:
    com.wzw.seckill.mapper: debug


